services:
  - type: web
    name: mindguard
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m textblob.download_corpora
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0